### ISSUE TITLE
M03-Unit 5 Provision an ExpressRoute circuit.md: ENG version updates being translated soon?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp#2]
This set of instructions has had an update in the ENG version, hopefully it will soon be translated and updated here?  Note that with this change it is important to have an updated screenshot showing the new settings.  I am including a reference to the ENG version highlighting the important changes:

![image](https://user-images.githubusercontent.com/49700217/203122747-10cf5052-533a-4aea-9257-0e5c49de68e7.png)

**Comment by chriscarty00** [comment]
added US file manually as per PM instructions.
