### ISSUE TITLE
M07-Unit 5 Restrict network access to PaaS resources with virtual network service endpoints - issues with screenshots

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp#3]
In Task 10, Step 9, the screenshot of the expected error message has changed and now looks like this:

![image](https://user-images.githubusercontent.com/49700217/203179004-30634e83-19b6-4fd1-89dd-662556007681.png)

In several other screenshots, it appears that they are either from a different course (DP-300) or from an old version of the instructions.  Some examples here:

**-Existing screenshots from a DP-300 course?**
![image](https://user-images.githubusercontent.com/49700217/203179223-4758785d-641a-4d2f-8d28-b8ce19b42550.png)

**-Existing screenshot:** Doesn't match the values students would have after following instructions:
![image](https://user-images.githubusercontent.com/49700217/203180364-08699226-5fd0-46fc-bb37-fab83346af1c.png)

When properly configured it *should* look like this (note the specific names 'public' and 'private', and the /24)
![image](https://user-images.githubusercontent.com/49700217/203180497-d2c42d23-422f-4843-a7ce-dc70216f523c.png)

**-Existing screenshot:** Doesn't match the values students would have after following instructions:
![image](https://user-images.githubusercontent.com/49700217/203181971-af76015c-ce5c-4575-b7cd-f4ed909f4f6b.png)

When properly configured  it *should* look like this:
![image](https://user-images.githubusercontent.com/49700217/203182187-7fd82e76-483a-4fc0-9032-689067cd5e19.png)

While the existing screenshots may give a rough idea of what the Azure screen looks like generally, Students will often become confused and/or make irrecoverable errors if they can see the screenshots do not precisely agree with the instructions, or if the instructions when followed in their lab instances do not match the screenshots.

Best practice is to obtain new/specific screenshots from this exact course, when QA'ing it from up-to-date Instructions, and to be certain that all screenshot details exactly match what the student should see at that point in the Lab, including such information matching the instructions such as Resource Group names, IP ranges, VNet names, etc.  (I know this can be tedious and time consuming, but students will complain - we have had several reports of exactly this issue recently from confused students, which is why I am posting this)

**Comment by chriscarty00** [comment]
ja-JP is like en-us here 
Tagging for the WWL team to review but closing
