### ISSUE TITLE
Update 01-provision-sql-vm.md

### ISSUE THREAD

**Issue by chriscarty00** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp#6]
File :  01-provision-sql-vm.md

Reviewer proposed an extra line to be added to  01-provision-sql-vm.md

- **イメージ:** 無料の SQL Server ライセンス: Windows Server 2022 上の SQL 2019 Developer - Gen1
    - **Azure スポット インスタンス:** なし (オフ)

  - **セキュリティの種類:** Standard
    - **イメージ:** Free SQL Server License: SQL 2019 Developer on Windows Server 2022 - Gen1
    - **Azure スポット 割引:** なし (オフ)

![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp/assets/63402128/8a700919-9272-4d42-97c8-4af759894fd5)

**Comment by chriscarty00** [comment]
Needs WWL to add this line to core en-us file if needed

**Comment by stonezy123** [comment]
Now, the 01-provision-sql-vm.md was deleted. close this issue.
