### ISSUE TITLE
EN-US update to CAICritical_6960779_M05-Unit+6+Create+a+front+door+for+a+highly+available+web+application+using+the+Azure+portal.md

### ISSUE THREAD

**Issue by chriscarty00** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp#7]
Reviewer is suggesting a  chnage to Japanese but this if approved needs to be made to the core en-us file

![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp/assets/63402128/ac73fff8-792e-4926-80ba-c9d3e228d0bb)

**Comment by chriscarty00** [comment]
Pull request : https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp/pull/5/commits/332b7849c497375f6f1a6b5c578ca2632977f9ff

**Comment by stonezy123** [comment]
The source string is **Select East US.**
https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/blob/master/Instructions/Exercises/M05-Unit%206%20Create%20a%20front%20door%20for%20a%20highly%20available%20web%20application%20using%20the%20Azure%20portal.md

so the translation sting is correct. **East US（米国東部）**
